common/models/Game.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "game".
 *
 * @property int $game_id
 * @property string $name
 * @property string $description
 * @property string $min_proc
 * @property string $min_video
 * @property string $min_ram
 * @property string $min_os
 * @property string $min_space
 * @property string $rec_proc
 * @property string $rec_vid
 * @property string $rec_ram
 * @property string $rec_os
 * @property string $rec_space
 * @property int $price
 * @property string|null $release_date
 * @property int|null $amount
 * @property string|null $image
 *
 * @property CompanyGame[] $companyGames
 * @property GenreGame[] $genreGames
 * @property Purchase[] $purchases
 * @property Review[] $reviews
 */
class Game extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'game';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'description', 'min_proc', 'min_video', 'min_ram', 'min_os', 'min_space', 'rec_proc', 'rec_vid', 'rec_ram', 'rec_os', 'rec_space', 'price'], 'required'],
            [['description'], 'string'],
            [['price', 'amount'], 'integer'],
            [['release_date'], 'safe'],
            [['name', 'image'], 'string', 'max' => 255],
            [['min_proc', 'min_video', 'rec_proc', 'rec_vid'], 'string', 'max' => 128],
            [['min_ram', 'min_space', 'rec_ram', 'rec_space'], 'string', 'max' => 30],
            [['min_os', 'rec_os'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'game_id' => 'Game ID',
            'name' => 'Name',
            'description' => 'Description',
            'min_proc' => 'Minimal required CPU',
            'min_video' => 'Minimal required GPU',
            'min_ram' => 'Minimal required RAM',
            'min_os' => 'Minimal required OS',
            'min_space' => 'Minimal required space',
            'rec_proc' => 'Recommended required CPU',
            'rec_vid' => 'Recommended required GPU',
            'rec_ram' => 'Recommended required RAM',
            'rec_os' => 'Recommended required OS',
            'rec_space' => 'Recommended required space',
            'price' => 'Price',
            'release_date' => 'Release Date',
            'amount' => 'Amount',
            'image' => 'Image',
        ];
    }

    /**
     * Gets query for [[CompanyGames]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCompanyGames()
    {
        return $this->hasMany(CompanyGame::className(), ['game_id' => 'game_id']);
    }

    /**
     * Gets query for [[GenreGames]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getGenreGames()
    {
        return $this->hasMany(GenreGame::className(), ['game_id' => 'game_id']);
    }

    /**
     * Gets query for [[Purchases]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPurchases()
    {
        return $this->hasMany(Purchase::className(), ['game_id' => 'game_id']);
    }

    /**
     * Gets query for [[Reviews]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getReviews()
    {
        return $this->hasMany(Review::className(), ['game_id' => 'game_id']);
    }
}

backend/controllers/GameController.php
<?php

namespace backend\controllers;

use backend\models\GameCreateForm;
use Yii;
use common\models\Game;
use backend\models\GameSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * GameController implements the CRUD actions for Game model.
 */
class GameController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Game models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new GameSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Game model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Game model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new GameCreateForm();

        if ($model->load(Yii::$app->request->post()) && $model->upload()) {
            $game = $this->insertToModel(null, $model);
            if ($game->save()) {
                return $this->redirect(['view', 'id' => $game->game_id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Game model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $game = $this->findModel($id);
        $model = $this->insertToForm($game);

        if ($model->load(Yii::$app->request->post()) && $model->upload()) {
            $game = $this->insertToModel($game, $model);
            if ($game->update()) {
                return $this->redirect(['view', 'id' => $game->game_id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'game_id' => $id
        ]);
    }


    /**
     * @param Game|null $game
     * @param GameCreateForm $form
     * @return Game
     */
    private function insertToModel($game, $form) {
        if (is_null($game)) {
            $game = new Game();
        }
        $game->image =        $form->imageName;
        $game->name =         $form->name;
        $game->description =  $form->description;
        $game->min_proc =     $form->min_proc;
        $game->min_os =       $form->min_os;
        $game->min_ram =      $form->min_ram;
        $game->min_space =    $form->min_space;
        $game->min_video =    $form->min_video;
        $game->rec_proc =     $form->rec_proc;
        $game->rec_os =       $form->rec_os;
        $game->rec_ram =      $form->rec_ram;
        $game->rec_space =    $form->rec_space;
        $game->rec_vid =      $form->rec_vid;
        $game->price =        $form->price;
        $game->release_date = $form->release_date ? $form->release_date : $game->release_date;
        $game->amount =       $form->amount;

        return $game;
    }

    /**
     * @param Game $model
     * @return GameCreateForm
     */
    private function insertToForm($model) {
        $form = new GameCreateForm();
        $form->imageName =    $model->image;
        $form->name =         $model->name;
        $form->description =  $model->description;
        $form->min_proc =     $model->min_proc;
        $form->min_os =       $model->min_os;
        $form->min_ram =      $model->min_ram;
        $form->min_space =    $model->min_space;
        $form->min_video =    $model->min_video;
        $form->rec_proc =     $model->rec_proc;
        $form->rec_os =       $model->rec_os;
        $form->rec_ram =      $model->rec_ram;
        $form->rec_space =    $model->rec_space;
        $form->rec_vid =      $model->rec_vid;
        $form->price =        $model->price;
        $form->release_date = $model->release_date ? $model->release_date : $form->release_date;
        $form->amount =       $model->amount;

        return $form;
    }

    /**
     * Deletes an existing Game model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Game model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Game the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Game::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/GameController.php
<?php

namespace frontend\controllers;

use common\models\Review;
use Yii;
use common\models\Game;
use frontend\models\GameSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * GameController implements the CRUD actions for Game model.
 */
class GameController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ]
        ];
    }

    /**
     * Lists all Game models.
     * @return mixed
     */
    public function actionIndex()
    {
        $games = Game::find()->all();

        return $this->render('index', [
            'games' => $games,
        ]);
    }

    /**
     * Displays a single Game model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = Review::findOne(['user_id' => Yii::$app->user->id, 'game_id' => $id]);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'review_model' => $model
        ]);
    }

    /**
     * Finds the Game model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Game the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Game::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/game/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\GameSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="game-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'min_proc') ?>

    <?= $form->field($model, 'min_video') ?>

    <?php // echo $form->field($model, 'min_ram') ?>

    <?php // echo $form->field($model, 'min_os') ?>

    <?php // echo $form->field($model, 'min_space') ?>

    <?php // echo $form->field($model, 'rec_proc') ?>

    <?php // echo $form->field($model, 'rec_vid') ?>

    <?php // echo $form->field($model, 'rec_ram') ?>

    <?php // echo $form->field($model, 'rec_os') ?>

    <?php // echo $form->field($model, 'rec_space') ?>

    <?php // echo $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'release_date') ?>

    <?php // echo $form->field($model, 'amount') ?>

    <?php // echo $form->field($model, 'image') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/game/index.php
<?php

use common\models\Game;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel frontend\models\GameSearch */
/* @var $games Game[] */

$this->title = 'Games';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="game-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php Pjax::begin(); ?>

    <div class="card-deck" style="margin-top: 10px">
        <? foreach ($games as $game): ?>
            <div class="card bg-success col-md-3 col-sm-6"
                 style="padding: 10px; border: 3px solid white; border-radius: 10px">
                <a href="<?= Url::to(['/game/view', 'id' => $game->game_id]) ?>">
                    <img src="<?= '\\backend\\web\\files\\img\\games\\'.$game->image ?>"
                         alt="<?= $game->name ?>" class="card-img-top d-block"
                         style="max-width: 100%; margin: auto">
                </a>
                <div class="card-body">
                    <h3 class="card-title"><?= $game->name ?></h3>
                    <p class="card-text">Release date: <?= $game->release_date ?></p>
                    <?
                    $rating = 0;
                    foreach ($game->reviews as $review) {
                        $rating += $review->rating;
                    }
                    if(count($game->reviews) > 0) $rating /= count($game->reviews)
                    ?>
                    <p class="card-text">Rating: <?= $rating ?></p>
                </div>
            </div>
        <? endforeach; ?>
    </div>

    <?php Pjax::end(); ?>

</div>

frontend/views/game/view.php
<?php

use common\models\Review;
use common\models\User;
use kartik\rating\StarRating;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Game */
/* @var $review_model Review */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);

$image = '\\backend\\web\\files\\img\\games\\'.$model->image;
?>
<div class="game-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="container genres">
        <? foreach ($model->genreGames as $genreGame): ?>
            <a class="badge badge-secondary" href="<?= Url::to(['/genre/view', 'id' => $genreGame->genre_id]) ?>">
                <?= $genreGame->genre->name ?>
            </a>
        <? endforeach; ?>
    </div>

    <div class="row" style="margin-top: 10px">
        <img src="<?= $image ?>" alt="<?= $model->name ?>" class="col-md-5 col-12">
        <div class="col-md-7 col-12">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'name',
                    'description:ntext',
                    'price',
                    'release_date',
                    'amount',
                ],
            ]) ?>

            <?
            $avg = 0;
            foreach ($model->reviews as $review) {
                $avg += $review->rating;
            }
            if (count($model->reviews) > 0) $avg /= count($model->reviews)
            ?>
            <h4>Total rating:</h4>
            <?= StarRating::widget([
                'name' => 'total_rating',
                'value' => $avg,
                'pluginOptions' => ['displayOnly' => true, 'step' => 0.1]
            ]) ?>
        </div>
    </div>

    <table class="table table-striped table-bordered mt-md-3" style="margin-top: 10px">
        <thead>
        <tr>
            <th></th>
            <th>Minimal properties</th>
            <th>Recommended properties</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>CPU</td>
            <td><?= $model->min_proc ?></td>
            <td><?= $model->rec_proc ?></td>
        </tr>
        <tr>
            <td>GPU</td>
            <td><?= $model->min_video ?></td>
            <td><?= $model->rec_vid ?></td>
        </tr>
        <tr>
            <td>RAM</td>
            <td><?= $model->min_ram ?></td>
            <td><?= $model->rec_ram ?></td>
        </tr>
        <tr>
            <td>Operational System</td>
            <td><?= $model->min_os ?></td>
            <td><?= $model->rec_os ?></td>
        </tr>
        <tr>
            <td>Disk</td>
            <td><?= $model->min_space ?></td>
            <td><?= $model->rec_space ?></td>
        </tr>
        </tbody>
    </table>
    <?= Html::a('Buy game', Url::to(['/purchase/create', 'id' => $model->game_id]),
        ['class' => 'btn btn-lg btn-success', 'style' => ['display' => 'block']]) ?>

    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a href="#companies" class="nav-link active" data-toggle="tab">Companies</a>
        </li>
        <li class="nav-item">
            <a href="#reviews" class="nav-link" data-toggle="tab">Reviews</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade active in" id="companies">
            <table class="table">
                <thead>
                <tr>
                    <th>Company name</th>
                    <th>Creation date</th>
                    <th>Country</th>
                </tr>
                </thead>
                <tbody>
                <? foreach ($model->companyGames as $companyGame): ?>
                    <tr>
                        <td><?= Html::a(Html::encode($companyGame->company->name),
                                Url::to(['/company/view', 'id' => $companyGame->company_id])); ?></td>
                        <td><?= $companyGame->company->creation_date ?></td>
                        <td><?= $companyGame->company->country ?></td>
                    </tr>
                <? endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="tab-pane fade" id="reviews">
            <?
            $reviewed = !is_null($review_model);
            if (!$reviewed) {
                echo Html::a('Add your review', Url::to(['/review/create', 'game_id' => $model->game_id]),
                ['class' => 'btn btn-primary']);
            }?>
            <ul class="list-group">
                <?
                if($reviewed): ?>
                <li class="list-group-item">
                    <h4><?= $review_model->user->username ?></h4>
                    <p><?=  $review_model->review_text ?></p>
                    <?= StarRating::widget([
                        'name' => 'rating'.$review_model->review_id,
                        'value' => $review_model->rating,
                        'pluginOptions' => ['displayOnly' => true]
                    ]) ?>
                    <?= Html::a('Edit review', ['/review/edit', 'id' => $review_model->review_id],
                        ['class' => 'btn btn-primary']) ?>
                </li>
                <? endif; ?>

            <? foreach($model->reviews as $review):
                if ($review->user_id != Yii::$app->user->id): ?>
                <li class="list-group-item">
                    <h4><?= $review->user->username ?></h4>
                    <p><?=  $review->review_text ?></p>
                    <?= StarRating::widget([
                        'name' => 'rating'.$review->review_id,
                        'value' => $review->rating,
                        'pluginOptions' => ['displayOnly' => true]
                    ]) ?>
                </li>
            <? endif;
            endforeach; ?>
            </ul>
        </div>
    </div>

</div>